##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [1]:
## write code here


In [2]:
import numpy as np
print(np.__version__)

1.23.5


#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [3]:
## write code here


In [4]:
arr=np.arange(1,17)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [5]:
## write code here


In [6]:
arr=np.arange(1,17)
arr[arr%2==1]


array([ 1,  3,  5,  7,  9, 11, 13, 15])

#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [7]:
## write code here


In [8]:
arr[arr%2==1] = 0
arr


array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16])

#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

In [9]:
## write code here


In [10]:
arr=np.random.randint(1,9, (4,4))
print(arr)

[[6 4 8 6]
 [8 5 3 6]
 [3 5 2 8]
 [1 6 8 7]]


#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [11]:
## write code here


In [12]:
ar=np.random.randint(1,8, (8,4))
ar

array([[1, 1, 5, 3],
       [2, 6, 4, 7],
       [3, 3, 5, 6],
       [5, 1, 4, 5],
       [7, 5, 5, 6],
       [2, 6, 2, 4],
       [4, 2, 6, 7],
       [2, 2, 2, 1]])

In [13]:
np.vstack((ar,ar)) 

array([[1, 1, 5, 3],
       [2, 6, 4, 7],
       [3, 3, 5, 6],
       [5, 1, 4, 5],
       [7, 5, 5, 6],
       [2, 6, 2, 4],
       [4, 2, 6, 7],
       [2, 2, 2, 1],
       [1, 1, 5, 3],
       [2, 6, 4, 7],
       [3, 3, 5, 6],
       [5, 1, 4, 5],
       [7, 5, 5, 6],
       [2, 6, 2, 4],
       [4, 2, 6, 7],
       [2, 2, 2, 1]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [14]:
## write code here


In [15]:
ar[:]

array([[1, 1, 5, 3],
       [2, 6, 4, 7],
       [3, 3, 5, 6],
       [5, 1, 4, 5],
       [7, 5, 5, 6],
       [2, 6, 2, 4],
       [4, 2, 6, 7],
       [2, 2, 2, 1]])

In [16]:
x=ar[:, [1,0,3,2]]
x

array([[1, 1, 3, 5],
       [6, 2, 7, 4],
       [3, 3, 6, 5],
       [1, 5, 5, 4],
       [5, 7, 6, 5],
       [6, 2, 4, 2],
       [2, 4, 7, 6],
       [2, 2, 1, 2]])

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [17]:
## write code here
mean=np.mean(ar)
median=np.median(ar)



In [18]:
mean


3.875

In [19]:
median

4.0

In [20]:
import statistics


In [23]:
 _, idx, count_ =np.unique(ar.reshape(32),return_counts=True, return_inverse=True)

In [25]:
index_=idx[np.argmax(count_)]

In [26]:
index_

0

In [28]:
mode=ar.reshape(32)[index_]

In [29]:
mode

1

# import statistics

In [51]:
marks=[75,85,45,7,5,75,5,2,55]

In [52]:
marks

[75, 85, 45, 7, 5, 75, 5, 2, 55]

In [53]:
dic= {i:marks.count(i) for i in marks}

In [54]:
dic

{75: 2, 85: 1, 45: 1, 7: 1, 5: 2, 2: 1, 55: 1}

In [55]:
max_= -12
ModE= None

for k,v in dic.items():
    if v>max_:
        ModE= k
        max_=v

In [48]:
ModE

75

In [49]:
statistics.mode(marks)

75

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

In [ ]:
## write code here


In [56]:
ar

array([[1, 1, 5, 3],
       [2, 6, 4, 7],
       [3, 3, 5, 6],
       [5, 1, 4, 5],
       [7, 5, 5, 6],
       [2, 6, 2, 4],
       [4, 2, 6, 7],
       [2, 2, 2, 1]])

In [63]:
random_arr=np.array[np.random.choice(ar.reshape(32) for i in range(5)]

SyntaxError: invalid syntax (475233134.py, line 1)

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [75]:
def BCE(y, y_hat):
    return (y*np.log(y_hat) - (1-y)*np.log(1-y_hat)).mean()
    ## write code here
    

In [76]:
y

array([0.13, 0.2 , 0.3 , 0.4 , 0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 0.1 ])

In [77]:
y_hat

array([0.2, 0.3, 0.4, 0.3, 0.6, 0.8, 0.7, 0.5, 0.8, 0.1])

In [78]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.007749312731669802


In [81]:
BCE(y, y_hat)

0.007749312731669802